import { ArtDef } from './raster';
import { rows, stamp } from './helpers';
const ice = { h: '#f0fbff', c: '#acdbea', b: '#588cb1', d: '#2e5175', q: '#b9e4f5fa' };
// Wide frozen root at y=0. The tip reaches the last row, so the sprite is
// attached to the roof and the requested height is its visible length.
function icicle(width: number, bend: number): string[] {
  return Array.from({ length: 32 }, (_, y) => {
    const half = Math.max(0, Math.floor(width * Math.pow(1 - y / 32, 1.5)));
    const mid = 15 + Math.round(bend * y / 31);
    return Array.from({ length: 32 }, (_, x) => {
      const d = x - mid;
      if (Math.abs(d) > half) return '.';
      if (d === -half) return y < 4 ? 'q' : 'h';
      return d < 0 ? 'c' : d === 0 ? 'b' : 'd';
    }).join('');
  });
}
// A low spoil mound, held together by branching roots rather than a bag-shaped
// outline. An exposed shard and a dark hollow suggest something buried inside.
const earth = rows(`
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ...........aa..aaa..............
  .........aabbaabbbaa............
  ........abbcbbbccbbba...........
  ......aabbcbbbccbbbbbaa.........
  .....abbcbccbbbbbbbcbbba........
  ....abbbbcbbbbbbbbbccbbba.......
  ...abccbbbbbbaaaabbbbbbcbaa.....
  ..aabbbbbbbaaakkkaabbbbcbbba....
  ..abbbccbaaakkppkkaabbbbbbbba...
  .abbbbcbbakpphhppkkaabbbbccba...
  .abbbbbbaaappphhpkaabbcbbbbbba..
  aabbccbbbbaaaappaabbbbbccbbbba..
  abbbbcbbbbbaaaaabbbbcbbbbbbbbaa.
  .aabbbbbccbbbbbbbbbbccbbbbbaa...
  aaabbbbbbbbbbcbbbbbbbbbbcbaaa...
  ..aaaabbbbcccbbbbbccbbbbaaa.....
  .a...aaaabbbbbbbbbbbbaaaa..a....
  ....a...aaaaaaaaaaaaa.....aa....
  ..........aa.....aaa............
  ................................
`);
const roots = rows(`
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ..........rt..r.................
  ..........rur.rr................
  ...........rurr.................
  ...........rttr......rt.........
  ..........rrutr.....rur.........
  .........rrutrr....rur..........
  ........rrutr....rrur...........
  ......rrrutr....rrurr...........
  .....rrtutr....rrurr............
  ....rrutr.....rrurr.............
  ....rutr......rutr..............
  ...rrttr......rttr..............
  ...rutr.......rtur..............
  ..rrutr.......rrutr.............
  .rrutr.........rrutrr...........
  ..rutr...........rrutrr.........
  ..rttr............rrtutrr.......
  ...rutr.....rrrr...rrrtutrr.....
  ...rrutrrrrrtutrrrrrr..rrutr....
  ....rrtutttutrrttutrr....rttr...
  .....rrrrrrrr...rrutrr....rrur..
  ....rr...........rrtr......rr...
  ...................rr..........
  ................................
`);
const cache = stamp(earth.map(row => row.padEnd(32, '.').slice(0, 32)), roots);
const rubble = rows(`
  ......rur...........rur.........
  .....rrur..........rur..........
  ..aarutrr..aa....rrttr..aaa.....
  .abbutrba.abbba..rutr..abbba....
  aabbbtrbaabbccbaarrurbabbcbbaa..
  .abbbbrraaabbbbaaabtrabbccba...
  ..aaaarrrtttrraaabbbrraabbaa...
  .aa..aaarrrra..aaabbaa.aaa....
  ....aa...a......aaaa.....a.....
`);
const rootPalette = { k: '#15110e', a: '#302218', b: '#503821', c: '#6d4b2e', r: '#38291d', t: '#967044', u: '#c49b61', p: '#87745b', h: '#b7a181' };
export const BIOME_PROPS: ArtDef[] = [
  { id: 'icicle_stub', palette: ice, rows: icicle(10, 0) },
  { id: 'icicle_spike', palette: ice, rows: icicle(6, 1) },
  { id: 'icicle_fang', palette: ice, rows: icicle(4, -2) },
  { id: 'root_cache', palette: rootPalette, rows: cache.map((row) => row.padEnd(32, '.').slice(0, 32)) },
  { id: 'root_cache_broken', palette: rootPalette, rows: stamp(Array.from({ length: 32 }, () => '.'.repeat(32)), rubble, 0, 22) },
];
