import { ArtDef } from './raster';
import { rows, stamp } from './helpers';
const ice = { h: '#f0fbff', c: '#acdbea', b: '#588cb1', d: '#2e5175', q: '#b9e4f5fa' };
// Wide frozen root at y=0. The tip reaches the last row, so the sprite is
// attached to the roof and the requested height is its visible length.
function icicle(width: number, bend: number): string[] {
  return Array.from({ length: 32 }, (_, y) => {
    const half = Math.max(0, Math.floor(width * Math.pow(1 - y / 32, 1.5)));
    const mid = 15 + Math.round(bend * y / 31);
    return Array.from({ length: 32 }, (_, x) => {
      const d = x - mid;
      if (Math.abs(d) > half) return '.';
      if (d === -half) return y < 4 ? 'q' : 'h';
      return d < 0 ? 'c' : d === 0 ? 'b' : 'd';
    }).join('');
  });
}
const cache = rows(`
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  .............rr.................
  ............rtr.................
  ..........rrttrrr...............
  ........rrabbbaaar..............
  .......rabbbcbcbbarr............
  ......rabbbrtbbbbbbar...........
  .....rabbbbrtrbcbbbbbar.........
  ....rabbbbrttrbbbbbbbbarr.......
  ...rabbbbrttrbbbccbbbbbbbar.....
  ..rabbbrtttrbbbbccbbbbbbbbar....
  .rabbbrttrbbbbbbbbbrtbbbbbar....
  .rbbbrtrbbbbbbbbbbbrtrbbbbbar...
  rabbrtrbbbbccbbbbbbrttrbbbbbar..
  rabbrtrbbbccccbbbbbrbttrbbbbbar.
  rabbbrtrbbbccbbbbbrbbbtrbbbbbar.
  rabbbbrtrbbbbbbbrtbbbbrtrbbbbbar
  rabbbbbrttrbbbbrtbbbbbrtrbbbbbar
  .rabbbbbrttrrrttbbbbbrtrbbbbar..
  ..rabbbbbrrttrrbbbbbrtrbbbbar...
  ...raabbbbrtrbbbbbrtrbbbbaar....
  ....rraaaabrtrbbbrtrbaaaarr.....
  ......rrrrrrtrrrrtrrrrrr........
  ............rr...rr.............
  ................................
`);
const rubble = rows(`
  ....rrrr........rrrr............
  ..rrabbr.......rtaar............
  .rabccbar.....rttabr...rr.......
  ..rabbar...rr..rrr...rabbar.....
  ...rrr...rabbar......rrr.......
  .........rrrr...................
`);
export const BIOME_PROPS: ArtDef[] = [
  { id: 'icicle_stub', palette: ice, rows: icicle(10, 0) },
  { id: 'icicle_spike', palette: ice, rows: icicle(6, 1) },
  { id: 'icicle_fang', palette: ice, rows: icicle(4, -2) },
  { id: 'root_cache', palette: { r: '#271b13', t: '#987446', a: '#473323', b: '#705034', c: '#b1844a' }, rows: cache.map((row) => row.padEnd(32, '.').slice(0, 32)) },
  { id: 'root_cache_broken', palette: { r: '#271b13', t: '#987446', a: '#473323', b: '#705034', c: '#b1844a' }, rows: stamp(Array.from({ length: 32 }, () => '.'.repeat(32)), rubble, 0, 25) },
];
