import { ArtDef } from './raster';
import { fill, rows, stamp } from './helpers';
import { ENEMY_ART_A } from './enemies-a';
import { ENEMY_ART_B } from './enemies-b';

// These are separate 32px frames, with equipment and silhouettes visible even
// before their attack windup. The underlying bodies keep the game's pixel style.
const original = new Map([...ENEMY_ART_A, ...ENEMY_ART_B].map((art) => [art.id, art]));
function frame(id: string, from: string, overlay: string[], x: number, y: number, colors: Record<string, string>): ArtDef {
  const source = original.get(from)!;
  return { id, palette: { ...source.palette, ...colors }, rows: stamp(source.rows, overlay, x, y) };
}

const drownedColors = { A: '#183c45', B: '#4f8586', C: '#9bc5bc', D: '#17191b', E: '#7c9999', F: '#b3e7e1fa' };
// A two-handed maul: head, then a haft thick enough to cover the raised sword
// it replaces. At one pixel the haft left the skeleton's own blade showing
// through beside it, and the head read as a box floating near the hand.
const drownedMaul = rows(`
  .DDDDDDD
  DBBBBBBD
  DBACACBD
  DBBBBBBD
  .DDDEDDD
  ...DEED.
  ...DEED.
  ...DEED.
  ...DEED.
  ...DEED.
  ...DEED.
  ...DEED.
  ...DEED.
  ...DEED.
`);
const drownedCrown = rows(`
  .A...A...A.
  .AB.BAB.BA.
  ..ABBBBBA..
  ...ABBBA...
  ..AF...FA..
`);

const stalkerColors = { A: '#191522', B: '#483350', C: '#a85d9f', D: '#f3c863fa', E: '#0a090e' };
/**
 * The bite. A stalker is a spider with a crest, and a crest three pixels higher
 * is not a tell you can read across a room — so the attack frame spreads a pair
 * of lit fangs under the eyes, which is the one part of it that catches light.
 */
const stalkerFangs = rows(`
  EDE....EDE
  .EDE..EDE.
  .EDE..EDE.
  ..EDEEDE..
  ...E..E...
`);
const stalkerCrest = rows(`
  A..............A
  BA............AB
  .CBA........ABC.
  ..CCBA....ABCC..
  ...CCBBBBBBCC...
  ....BBDDDDBB....
  .....BDDDDB.....
`);

const iceColors = { A: '#102638', B: '#346b94', C: '#8fd8f1', D: '#e1f8ff', E: '#b7eafffa' };
const iceCrest = rows(`
  .....C.....
  ....CDC....
  ...CDDDDC..
  ..CCCCCCC..
  ...BAAAB...
`);
const iceShield = rows(`
  ....C....
  ...CDC...
  ..CDDDC..
  .CDDBDDC.
  CDDDBDDDC
  CDDDBDDDC
  CDDDBDDDC
  .CDDBDDC.
  ..CDDDC..
  ...CDC...
  ....C....
`);

// The skeleton it is built from carries a sword. Clear the blade before the
// maul goes on, or the idle frame holds both and reads as neither.
const eraseSword = fill(6, 18, '_');
const drownedIdle = stamp(stamp(original.get('skeleton_0')!.rows, eraseSword, 23, 8), drownedCrown, 10, 0);
const drownedAttack = stamp(original.get('skeleton_atk')!.rows, drownedCrown, 10, 0);

const stalkerAttack = frame('stalker_atk', 'spider_atk', stalkerCrest, 8, 5, stalkerColors);
const stalkerBite: ArtDef = { ...stalkerAttack, rows: stamp(stalkerAttack.rows, stalkerFangs, 11, 16) };


/**
 * The Gravecaller: a hooded, robed skeleton that leans on a staff crowned
 * with a small skull. Its own eyes and the staff skull's burn the same sickly
 * green its chant throws onto the corpse, so the one that is doing the calling
 * reads across a room. The attack frame lifts the staff into a flare of that
 * green: the chant, and its weak blow, share the pose.
 */
const gravecallerColors = {
  k: '#0e0c0a', w: '#e2d9c2', v: '#aa9e84', g: '#8ce07afa', G: '#c8ffb8b0',
  a: '#1a221c', b: '#2e3f33', c: '#4d6650', h: '#5a3a1a',
};
const gravecallerIdle = rows(`
  ................................
  .......................kkkkk....
  ......................kwwwwwk...
  ..........kkkkkkkk....kwgwgwk...
  .........kbbbbbbbbk...kwwkwwk...
  ........kbbaaaaaabbk...kwwwk....
  ........kbakkkkkkabk....khk.....
  .......kbak......kabk...khk.....
  .......kbak.gk.kg.kabk..khk.....
  .......kbak..kwk..kabk..khk.....
  .......kbak.kvwvk.kabk..khk.....
  .......kbbak.kkk.kabbk..khk.....
  ........kbbakkkkkabbk...khk.....
  .......kbbbbaaaaabbbbk.kwhk.....
  ......kbbbbbbaaabbbbbbkwwhk.....
  .....kbbcbbbbbabbbbbcbkkwhk.....
  .....kbbcbbbbbabbbbbcbk.khk.....
  .....kbbkbbbbbabbbbbkbk.khk.....
  .....kwwkbbbbbabbbbbk...khk.....
  .....kvwkbbbbbabbbbbk...khk.....
  ......kk.kbbbbabbbbbk...khk.....
  ........kbbbbbabbbbbk...khk.....
  ........kbbbbbabbbbbbk..khk.....
  ........kbbbbbabbbbbbk..khk.....
  .......kbbbbbbabbbbbbbk.khk.....
  .......kbbbbbbabbbbbbbk.khk.....
  .......kbbcbbbabbbcbbbk.khk.....
  ......kbbbcbbbabbbcbbbbkkhk.....
  ......kbabbabbbbbabbabk..khk....
  ......kakbkakbkakbkakbk..kkk....
  .......k.k.k.k.k.k.k.k..........
  ................................
`);

const gravecallerChant = rows(`
  ......................kkkkk..G..
  ....................Gkwwwwwk..G.
  ...................G.kwGwGwk.G..
  ..........kkkkkkkk..Gkwwkwwk..G.
  .........kbbbbbbbbk...kwwwk..G..
  ........kbbaaaaaabbk...khk.G....
  ........kbakkkkkkabk...khk......
  .......kbak......kabk..khk......
  .......kbak.Gk.kG.kabk.khk......
  .......kbak..kwk..kabk.khk......
  .......kbak.kvwvk.kabkkwhk......
  .......kbbak.kkk.kabbkwwhk......
  ........kbbakkkkkabbkkwwhk......
  .......kbbbbaaaaabbbbkkkhk......
  ......kbbbbbbaaabbbbbbk.khk.....
  .....kbbcbbbbbabbbbbcbk.khk.....
  .....kbbcbbbbbabbbbbcbk.khk.....
  .....kbbkbbbbbabbbbbkbk.khk.....
  .....kwwkbbbbbabbbbbk...khk.....
  .....kvwkbbbbbabbbbbk...khk.....
  ......kk.kbbbbabbbbbk...khk.....
  ........kbbbbbabbbbbk...khk.....
  ........kbbbbbabbbbbbk..khk.....
  ........kbbbbbabbbbbbk..khk.....
  .......kbbbbbbabbbbbbbk.khk.....
  .......kbbbbbbabbbbbbbk.khk.....
  .......kbbcbbbabbbcbbbk.khk.....
  ......kbbbcbbbabbbcbbbbk.khk....
  ......kbabbabbbbbabbabk..kkk....
  ......kakbkakbkakbkakbk.........
  .......k.k.k.k.k.k.k.k..........
  ................................
`);


/**
 * The Goblin Quartermaster: a goblin under a tall war banner, red with a gold
 * mark, so the one giving the orders stands out of a goblin crowd. The Hoarder:
 * a giant rat bloated round a sack of coin, the sack's gold the thing you see.
 */
const quartermasterColors = { B: '#a83028', Y: '#e8c060', P: '#6a4424', K: '#120e08' };
const quartermasterBanner = rows(`
  KKKKKKK
  KBBBBBK
  KBBYBBK
  KBYYYBK
  KBBYBBK
  KBBBBK.
  KBBBK..
  KBBK...
  KP.....
  KP.....
  KP.....
  KP.....
  KP.....
  KP.....
  KP.....
  KP.....
`);
const hoarderColors = { G: '#b08a30', H: '#6a5020', Y: '#ffe890fa', Q: '#2a1c0c' };
const hoarderSack = rows(`
  ....QQQQ....
  ...QHHHHQ...
  ..QQQQQQQQ..
  .QGGGGGGGGQ.
  QGGGYGGGGGGQ
  QGGGGGGGYGGQ
  QGGYGGGGGGGQ
  QGGGGGGGGGGQ
  .QGGGGGYGGQ.
  ..QQQQQQQQ..
`);

export const ENEMY_ART_VARIETY: ArtDef[] = [
  frame('quartermaster_0', 'goblin_0', quartermasterBanner, 0, 2, quartermasterColors),
  frame('quartermaster_atk', 'goblin_atk', quartermasterBanner, 0, 2, quartermasterColors),
  frame('hoarder_0', 'rat_0', hoarderSack, 10, 6, hoarderColors),
  frame('hoarder_atk', 'rat_atk', hoarderSack, 10, 4, hoarderColors),
  { id: 'gravecaller_0', palette: gravecallerColors, rows: gravecallerIdle },
  { id: 'gravecaller_atk', palette: gravecallerColors, rows: gravecallerChant },
  { id: 'drowned_0', palette: { ...original.get('skeleton_0')!.palette, ...drownedColors }, rows: stamp(drownedIdle, drownedMaul, 22, 10) },
  { id: 'drowned_atk', palette: { ...original.get('skeleton_atk')!.palette, ...drownedColors }, rows: stamp(drownedAttack, drownedMaul, 21, 0) },
  frame('stalker_0', 'spider_0', stalkerCrest, 8, 8, stalkerColors),
  stalkerBite,
  { id: 'iceguard_0', palette: { ...original.get('skelshield_0')!.palette, ...iceColors }, rows: stamp(stamp(original.get('skelshield_0')!.rows, iceCrest, 10, 0), iceShield, 1, 17) },
  { id: 'iceguard_block', palette: { ...original.get('skelshield_block')!.palette, ...iceColors }, rows: stamp(stamp(original.get('skelshield_block')!.rows, iceCrest, 10, 0), iceShield, 9, 13) },
  { id: 'iceguard_atk', palette: { ...original.get('skelshield_atk')!.palette, ...iceColors }, rows: stamp(stamp(original.get('skelshield_atk')!.rows, iceCrest, 10, 0), iceShield, 1, 15) },
];
