import { ArtDef } from './raster';
import { rows, stamp, sym } from './helpers';

// Emissive colours end in 'fa' (see textures.ts).

const CHEST_LOWER = [
  '..kkkkkkkkkkkkkg',
  '..kwwwwwwwwwwkgh',
  '..kwwwywwwwwwkgh',
  '..kiiniiiiiiikgg',
  '..kwwwwwwwwwwwkk',
  '..kwwwwwwwwywwww',
  '..kwwwwwwwwwwwww',
  '..kiiniiiiiiiiii',
  '..kyyyyyyyyyyyyy',
  '..kkkkkkkkkkkkkk',
  '...zzzzzzzzzzzzz',
  '................',
  '................',
  '................',
];

const CHEST = sym([
  ...Array.from({ length: 11 }, () => '................'),
  '....kkkkkkkkkkkk',
  '...kxxxxxxxxxxxx',
  '..kxwwwwwwwwwwww',
  '..kwwwwywwwwwwww',
  '..kiiniiiiiiiiii',
  '..kwwwwwwwwwwwyw',
  '..kyyyyyyyyyyyyy',
  ...CHEST_LOWER,
]);

const CHEST_OPEN = sym([
  ...Array.from({ length: 6 }, () => '................'),
  '....kkkkkkkkkkkk',
  '...kyyyyyyyyyyyy',
  '..kyqqqqqqqqqqqq',
  '..kyqqqqqqqqqqqq',
  '..kyqqqqqqqqqqqq',
  '..kiiniiiiiiiiii',
  '..kxxxxxxxxxxxxx',
  '..kkkkkkkkkkkkkk',
  '..kqqqqqqqqqqqqq',
  '..kqqhgqqqqghqqq',
  '..kqhgghqqhgghqh',
  '..kqgghhghgghhgg',
  ...CHEST_LOWER,
]);

// An opened chest smashed flat: the lid gone, the sides snapped to splinters
// above the lower iron band. It stays on the floor like a broken urn does.
const CHEST_BROKEN = sym([
  ...Array.from({ length: 18 }, () => '................'),
  '....k.......k...',
  '...kxk.....kxk..',
  '..kwwk..k..kwwk.',
  '..kwyk.kxk.kwwkk',
  '..kiinkkwwkkiiii',
  '..kwwwwwwwwwwwww',
  '..kwwwwwwwwywwww',
  '..kiiniiiiiiiiii',
  '..kyyyyyyyyyyyyy',
  '..kkkkkkkkkkkkkk',
  '...zzzzzzzzzzzzz',
  '................',
  '................',
  '................',
]);

const CHEST_PAL = {
  k: '#120a05', x: '#8a5c30', w: '#6a4222', y: '#44280f', q: '#1e1008',
  i: '#34343c', n: '#8a8a94', g: '#c09030', h: '#f0d070', z: '#00000066',
  t: '#d8c89a', r: '#9c3028', m: '#8c2840',
};

// Two pale points in the lid seam are the whole tell. They read as worn nails
// until you have learned what they really are.
const CHEST_MIMIC = stamp(CHEST, rows(`
  t....t
`), 13, 17);

const MIMIC_FACE = rows(`
  ....r......r....
  ................
  ..tttttttttttt..
  ...ktktktktkt...
  ......mmmm......
  .......mm.......
`);
// Lid thrown back and the whole box turned into a mouth. The old attack frame
// widened the tongue and nothing else, which on a creature the player is
// already standing next to is no warning at all.
const MIMIC_FACE_ATK = rows(`
  ...rr........rr...
  ..................
  .tttttttttttttttt.
  ..tktktktktktktk..
  ..mmmmmmmmmmmmmm..
  ..mmmmmmmmmmmmmm..
  ...mmtmmmmmmtmm...
  ....mmmmmmmmmm....
  .....mmmmmmmm.....
`);
// Four jointed legs unfold from each side of the box. The last three rows sit
// below the old chest silhouette, so the transformation changes its outline.
const MIMIC_LEGS = sym(rows(`
  ..k......k......
  .kxk....kxk.....
  kx.xk..kx.xk....
  x...k..x...k....
  ....k......k....
  ...kk.....kk....
  ...x.......x....
  ..kx.......xk...
  ..kk.......kk...
`));
const MIMIC_IDLE = stamp(stamp(CHEST_OPEN, MIMIC_FACE, 8, 8), MIMIC_LEGS, 0, 23);
const MIMIC_ATK = stamp(stamp(CHEST_OPEN, MIMIC_FACE_ATK, 7, 7), MIMIC_LEGS, 0, 23);

const URN = sym(rows(`
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ..........kkkkkk
  .........kddcccc
  .........kbbbbbb
  ..........kkeeee
  ..........kbbbcc
  ........kkbbbccc
  ......kkbbbbcccd
  .....kbbbbbccccd
  ....kaeeeeeeeeee
  ....kabbbbbcccdd
  ...kaabbbbbccccd
  ...kaabbbbbbcccc
  ...kaabbbbbbbccc
  ...kaaabbbbbbbbc
  ....kaaabbbbbbbb
  ....kaaaabbbbbbb
  .....kkaaaaaaaaa
  .......kkkkkkkkk
  ................
  ................
`));

const URN_BROKEN = sym(rows(`
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ........kk....kk
  .......kdk...kbb
  ....kkkabkkkbbcc
  ...kaabbbbbbcccd
  ...kaaabbbbbbbcc
  ....kaaabbbbbbbb
  .....kkaaaaaaaaa
  .......kkkkkkkkk
  ..k.kd.......kdk
  ...kk........kk.
`));

const URN_PAL = { k: '#140a06', a: '#4a2616', b: '#7a4428', c: '#9a5c34', d: '#c07a48', e: '#2e160c' };

/** Bulging in the middle, staves shaded round the curve, four iron hoops that each catch the light once. */
const BARREL = rows(`
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ......kkkkkkkkkkkkkkkkkkkk......
  .....kyllllllllllllllllllyk.....
  ....kywyyyyyyyyyyyyyyyyyyyyk....
  ....kiiijjiiiiiiiiiiiiiiiiik....
  ...kywwwyxxxyxwwwwywwvyvvvyyk...
  ...kywwwyxxxyxwwwwywwvyvvvyyk...
  ...kywwwyxxxyxwwwwywwvyvvvyyk...
  ..kiiijjiiiiiiiiiiiiiiiiiiiiik..
  ..kywwwywxxxyxwwwwywwwvyvvvyyk..
  ..kywwwywxxxyxwwwwywwwvyvvvyyk..
  ..kywwwywxxxyxwwwwywwwvyvvvyyk..
  ..kywwwywxxxyxwwwwywwwvyvvvyyk..
  ..kywwwywxxxyxwwwwywwwvyvvvyyk..
  ..kywwwywxxxyxwwwwywwwvyvvvyyk..
  ..kywwwywxxxyxwwwwywwwvyvvvyyk..
  ..kiiijjiiiiiiiiiiiiiiiiiiiiik..
  ...kywwwyxxxyxwwwwywwvyvvvyyk...
  ...kywwwyxxxyxwwwwywwvyvvvyyk...
  ...kywwwyxxxyxwwwwywwvyvvvyyk...
  ....kiiijjiiiiiiiiiiiiiiiiik....
  ....kywwywxxxywwwywwwvyvvyyk....
  .....kywwyxxxywwwywwvyvvyyk.....
  ......kkkkkkkkkkkkkkkkkkkk......
  ........zzzzzzzzzzzzzzzz........
`);

const BARREL_BROKEN = rows(`
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  .............k...kk.............
  ......kk....kxk.kwyk............
  ....kkwwk..kyxk.kwykk..k..kk....
  ...kykwwkkkkyxwkkwywwkkvkkyyk...
  ...kywwwyxxxyxwwwwywwvyvvvyyk...
  ..kywwwywxxxyxwwwwywwwvyvvvyyk..
  ..kiiijjiiiiiiiiiiiiiiiiiiiiik..
  ...kywwwyxxxyxwwwwywwvyvvvyyk...
  ...kywwwyxxxyxwwwwywwvyvvvyyk...
  ...kywwwyxxxyxwwwwywwvyvvvyyk...
  ....kiiijjiiiiiiiiiiiiiiiiik....
  ....kywwywxxxywwwywwwvyvvyyk....
  ...kkkywwyxxxywwwywwvyvvyyk.....
  ..kwwwwwkkkkkkkkkkkkkkkkkkkkk...
  ...kkkkkzzzzzzzzzzzzzzzkwwwwwk..
`);

const BARREL_PAL = { k: '#120a05', x: '#8a5a30', w: '#6a4222', v: '#523218', l: '#7a5028', y: '#3a220c', i: '#2e2e36', j: '#6a6a78', z: '#00000066' };

const BONES = rows(`
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ..........kkk...................
  .........kwwwk.......k..........
  ........kwkwkwk.....kwk.........
  ........kwwwwwk....kwvk..kk.....
  .........kwkwk....kwvk..kwwk....
  ..kk......kkk....kwvk..kwvvwk...
  .kwwkkkkkkkkkk..kwvk....kkkk....
  .kwvvvvvvvvvvwk.kkk.............
  ..kkkkkkkkkkkk..................
`);

const SHRINE = sym(rows(`
  ................
  ................
  ................
  ................
  ................
  ..............oy
  .............oyy
  .............oyy
  ..............oy
  ................
  ................
  ....f...........
  ...fyf..........
  ....y...........
  ....w...........
  ...kwk..........
  ...kwk..........
  ..kkkkkkkkkkkkkk
  ..kddddddddddddd
  ..kccccccccccccc
  ..kkkkkkkkkkkkkk
  ...kcbbbbbbbbbbb
  ...kcbbbbbkkkkkk
  ...kcbbbbkvwwwww
  ...kcbbbbkwkkwww
  ...kcbbbbkwkkwww
  ...kcbbbbkvwwwwk
  ...kcbbbbbkvwkwk
  ...kcbbbbbbkkkkk
  ..kkkkkkkkkkkkkk
  ..kddddddddddddd
  ..kaaaaaaaaaaaaa
`));

const SHRINE_OFF = rows(`
  ................................
  ................................
  ................................
  ................................
  ................................
  ______________________________..
  ______________________________..
  ______________________________..
  ______________________________..
  ................................
  ................................
  ________________________________
  ________________________________
  ________________________________
  ................................
`);

// The stone's cast and everything that glows change colour per god — the part
// your eye finds first in a dark room, so you can read a shrine from across it
// before you commit. The object on the plinth tells you the rest up close.
const SHRINE_PAL = {
  k: '#0e0d10', d: '#6a6874', c: '#54525e', b: '#403e48', a: '#2a2830',
  v: '#a89c80', w: '#e8e0c8', f: '#ffb040fa', y: '#fff0c0fa', o: '#7aa0fffa',
};
const SHRINE_FONT_PAL = {
  ...SHRINE_PAL,
  d: '#5c6e7a', c: '#48586a', b: '#36424e', a: '#222a34',
  f: '#40c8f0fa', y: '#c8f8fffa', o: '#60d8fffa',
};
const SHRINE_IDOL_PAL = {
  ...SHRINE_PAL,
  d: '#6a5c7a', c: '#54486a', b: '#40364e', a: '#2a2234',
  f: '#a040e0fa', y: '#e8b0fffa', o: '#c070fffa',
};
const SHRINE_COFFER_PAL = {
  ...SHRINE_PAL,
  d: '#7a6c4a', c: '#60543a', b: '#48402c', a: '#2e2a1c',
  f: '#ffb040fa', y: '#fff0c0fa', o: '#ffd060fa',
};
const SHRINE_BLOOD_PAL = {
  ...SHRINE_PAL,
  d: '#7a3a44', c: '#602e38', b: '#48222c', a: '#2e161c',
  f: '#ff4a5afa', y: '#ffc0c8fa', o: '#ff8090fa',
};
const SHRINE_COMBAT_PAL = {
  ...SHRINE_PAL,
  d: '#7a4c2e', c: '#603c24', b: '#482e1c', a: '#2e1e12',
  f: '#ff7a30fa', y: '#ffd8a8fa', o: '#ffa050fa',
};

/**
 * Each god gets its own thing on the plinth, and its own glyph cut into the
 * front, so a shrine says what it does before the prompt does: a brimming
 * font, a seated idol with lit eyes, a brass bowl heaped with coin, a bowl of
 * blood running over the edge, an ember brazier behind crossed blades. The
 * plinth and the candles stay shared, and the colour is still the tell from
 * across a dark room.
 */
// Cold clean water: it heals and washes curses away.
const SHRINE_FONT = rows(`
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ...........y.......y............
  .................o..............
  ..........kkkkkkkkkkkkk.........
  .........kdoooooooooooodk.......
  ....f....kcyooyoooooyoock..f....
  ...fyf....kcccccccccccck..fyf...
  ....y......kbbbbbbbbbbk....y....
  ....w.......kkcbbbbckk.....w....
  ...kwk........kcbbck......kwk...
  ...kwk........kcbbck......kwk...
  ..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kddddddddddddddddddddddddddk..
  ..kcccccccccccccccccccccccccck..
  ..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ...kcbbbbbbbbbbbbbbbbbbbbbbck...
  ...kcbbbbbkkkkkkkkkkkkbbbbbck...
  ...kcbbbbbkaaaaffaaaaabbbbbck...
  ...kcbbbbbkaaaffffaaaabbbbbck...
  ...kcbbbbbkaaffyfffaaabbbbbck...
  ...kcbbbbbkaaffffffaaabbbbbck...
  ...kcbbbbbkaaaffffaaaabbbbbck...
  ...kcbbbbbbbbbbbbbbbbbbbbbbck...
  ..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kddddddddddddddddddddddddddk..
  ..kaaaaaaaaaaaaaaaaaaaaaaaaaak..
`);
// It grants a blessing, or takes something.
const SHRINE_IDOL = rows(`
  ................................
  ................................
  ................................
  ................................
  ................................
  .............kkkkkk.............
  ............kddddddk............
  ...........kdccccccck...........
  ...........kcfkccfkck...........
  ...........kcckcckcck...........
  ............kccccccck...........
  ....f......kkkbbbbkkk......f....
  ...fyf....kcckbbbbkcck....fyf...
  ....y.....kcbbkbbkbbck.....y....
  ....w.....kcbbbbbbbbck.....w....
  ...kwk....kccbbbbbbcck....kwk...
  ...kwk.....kkkkkkkkkk.....kwk...
  ..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kddddddddddddddddddddddddddk..
  ..kcccccccccccccccccccccccccck..
  ..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ...kcbbbbbbbbbbbbbbbbbbbbbbck...
  ...kcbbbbbkkkkkkkkkkkkbbbbbck...
  ...kcbbbbbkaaaffffaaaabbbbbck...
  ...kcbbbbbkaafakkafaaabbbbbck...
  ...kcbbbbbkafakyykafaabbbbbck...
  ...kcbbbbbkaafakkafaaabbbbbck...
  ...kcbbbbbkaaaffffaaaabbbbbck...
  ...kcbbbbbbbbbbbbbbbbbbbbbbck...
  ..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kddddddddddddddddddddddddddk..
  ..kaaaaaaaaaaaaaaaaaaaaaaaaaak..
`);
// Coin in, blessing out.
const SHRINE_COFFER = rows(`
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  .............kk.kk..............
  ............kGGkGGk.............
  ...........kGgGkGgGk............
  ........kkkkkkkkkkkkkkk.........
  ....f..kGGGGGGGGGGGGGGGk...f....
  ...fyf.kgGgggggggggggGgk..fyf...
  ....y...kgggggggggggggk....y....
  ....w....kkgggggggggkk.....w....
  ...kwk.....kkkgggkkk......kwk...
  ...kwk.......kgggk........kwk...
  ..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kddddddddddddddddddddddddddk..
  ..kcccccccccccccccccccccccccck..
  ..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ...kcbbbbbbbbbbbbbbbbbbbbbbck...
  ...kcbbbbbkkkkkkkkkkkkbbbbbck...
  ...kcbbbbbkaaaffffaaaabbbbbck...
  ...kcbbbbbkaafykkyfaaabbbbbck...
  ...kcbbbbbkaafykkyfaaabbbbbck...
  ...kcbbbbbkaafykkyfaaabbbbbck...
  ...kcbbbbbkaaaffffaaaabbbbbck...
  ...kcbbbbbbbbbbbbbbbbbbbbbbck...
  ..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kddddddddddddddddddddddddddk..
  ..kaaaaaaaaaaaaaaaaaaaaaaaaaak..
`);
// Blood in, gold out.
const SHRINE_BLOOD = rows(`
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  .........kkkkkkkkkkkkkk.........
  ........kGGGGGGGGGGGGGGk........
  ....f...kgRRRRRrRRRRRRgk...f....
  ...fyf...kgggggggggggRk...fyf...
  ....y.....kkgggggggkkr.....y....
  ....w.......kkgggkk..r.....w....
  ...kwk........kgggk.......kwk...
  ...kwk........kgggk.......kwk...
  ..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kddddddddddddddddddrdddddddk..
  ..kccccccccccccccccccrccccccck..
  ..kkkkkkkkkkkkkkkkkkkrkkkkkkkk..
  ...kcbbbbbbbbbbbbbbbbRbbbbbck...
  ...kcbbbbbkkkkkkkkkkkkbbbbbck...
  ...kcbbbbbkaaaaffaaaaabbbbbck...
  ...kcbbbbbkaaaaffaaaaabbbbbck...
  ...kcbbbbbkaaaffffaaaabbbbbck...
  ...kcbbbbbkaaffyyffaaabbbbbck...
  ...kcbbbbbkaaaffffaaaabbbbbck...
  ...kcbbbbbbbbbbbbbbbbbbbbbbck...
  ..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kddddddddddddddddddddddddddk..
  ..kaaaaaaaaaaaaaaaaaaaaaaaaaak..
`);
// Light it and the trial rises.
const SHRINE_COMBAT = rows(`
  ................................
  ................................
  ................................
  ................................
  ................................
  .......Sk..............kS.......
  .......kSk............kSk.......
  ........kSk....y.....kSk........
  .........kSk..yfy...kSk.........
  ..........kSk.fyf..kSk..........
  ...........kSkfyff.Sk...........
  ....f.....kkkSfffySkkk.....f....
  ...fyf...kiiiikSkSiiiik...fyf...
  ....y....kjiiiiSkiiiijk....y....
  ....w.....kiiiSkkSiiik.....w....
  ...kwk.....kkSk..kSkk.....kwk...
  ...kwk....kgk.kkkk..kgk...kwk...
  ..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kddddddddddddddddddddddddddk..
  ..kcccccccccccccccccccccccccck..
  ..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ...kcbbbbbbbbbbbbbbbbbbbbbbck...
  ...kcbbbbbkkkkkkkkkkkkbbbbbck...
  ...kcbbbbbkafaaaaaafaabbbbbck...
  ...kcbbbbbkaafaaaafaaabbbbbck...
  ...kcbbbbbkaaafaafaaaabbbbbck...
  ...kcbbbbbkaaaaffaaaaabbbbbck...
  ...kcbbbbbkaaafaafaaaabbbbbck...
  ...kcbbbbbbbbbbbbbbbbbbbbbbck...
  ..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..
  ..kddddddddddddddddddddddddddk..
  ..kaaaaaaaaaaaaaaaaaaaaaaaaaak..
`);

/** A spent shrine: the candles are out and whatever glowed has gone to ash. */
const SNUFF = rows(`
  ___......................___
  ___......................___
  ___......................___
`);
const snuffed = (r: string[]) => stamp(r, SNUFF, 2, 11);
const SPENT = { f: '#4a4450', y: '#5a5460', o: '#34323c' };
const SHRINE_PROPS = { g: '#8a6a24', G: '#d8b048', r: '#7a0c18', R: '#c02030', i: '#3a2c24', j: '#5a4434', S: '#c8c8d8' };

/** Three glowing caps of different heights on a mossy foot; the spots are what light the room. */
const FUNGUS = rows(`
  ................
  ................
  ....kkkk........
  ...kcdcck.......
  ..kcdccdck......
  ..kccccdck......
  ..keeeeeek..kkk.
  ....ksk....kcdck
  .kkk.ksk..kcccdk
  kdcck.ksk.keeeek
  keeek.kssk..ksk.
  .ksk..kssk..ksk.
  .kssk.kssk..ksk.
  .kssk.kssk..kssk
  kmsskkmsskkkmssk
  .kmmmmmmmmmmmmk.
`);

/** A pitch-wrapped torch head in an iron wall bracket. The flame is its own sprite, set above. */
const SCONCE = rows(`
  ................
  ................
  ................
  ................
  .....kkkkkk.....
  ....kvuvvuvk....
  ....kuvuuvuk....
  .....kvuuvk.....
  ......khhk......
  ..kk..kjjk..kk..
  ..kikkkiikkkik..
  ...kiiiiiiiiik..
  ......khgk......
  ......khgk......
  .....kjiijk.....
  .....kkkkkk.....
`);

const FLAME_PAL = { r: '#ff6a10fa', o: '#ffa030fa', y: '#ffe070fa', w: '#fff8d0fa' };
const FLAME_0 = rows(`
  ................
  ................
  .......r........
  ......rr........
  ......ror.......
  .....roor.......
  .....royor......
  ....rooyor......
  ....royywor.....
  ....roywwyor....
  .....oywwyo.....
  .....rowwor.....
  ......roor......
  .......rr.......
  ................
  ................
`);
const FLAME_1 = rows(`
  ................
  ................
  ........r.......
  ........rr......
  .......ror......
  .......roor.....
  ......royor.....
  ......royoor....
  .....royywor....
  ....roywwyor....
  .....oywwyo.....
  .....rowwor.....
  ......roor......
  .......rr.......
  ................
  ................
`);
const FLAME_2 = rows(`
  ................
  ......r.........
  ......rr........
  .....ror........
  .....roor.......
  ....royor.......
  ....royoor......
  ....royyor......
  ....royywor.....
  ....roywwyor....
  .....oywwyo.....
  .....rowwor.....
  ......roor......
  .......rr.......
  ................
  ................
`);

const BAG = rows(`
  ................
  ................
  ................
  ......kk.kk.....
  .....k.kvk.k....
  ......kvsvk.....
  ......kuuvk.....
  .....kttuuuk....
  ....ktsttuuuk...
  ...ktsttuuuuvk..
  ..ktsttuuuuuvvk.
  ..ktttuuuuuuvvk.
  ..kttuuuuuuvvvk.
  ..ktuuuuuuuvvvk.
  ...kkuuuuuvvkk..
  .....kkkkkkk....
`);

const GOLD_PILE = rows(`
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  ................
  .......kk.......
  .....kkhykk.....
  ....khyhhhok....
  ...khhykhhhok...
  ..khyhhhkyhhok..
  .khhhhyhhhhhhok.
  .kkkkkkkkkkkkkk.
`);

const ORB = rows(`
  ................
  ................
  ................
  ......1111......
  .....122221.....
  ....12333321....
  ...1233443321...
  ...1234ww4321...
  ...1234ww4321...
  ...1233443321...
  ....12333321....
  .....122221.....
  ......1111......
  ................
  ................
  ................
`);

const ARROW = rows(`
  ................
  ................
  .............kk.
  ............kssk
  ...........kssk.
  ..........khk...
  .........hh.....
  ........hh......
  .......hh.......
  ......hh........
  ..f..hh.........
  ..ffhh..........
  ...fff..........
  ..f.ff..........
  ................
  ................
`);

const PROJ_KNIFE = rows(`
  ................
  ................
  ................
  ............k...
  ...........k4k..
  ..........k43k..
  .........k32k...
  ........khk.....
  .......khk......
  ......kk........
  ................
  ................
  ................
  ................
  ................
  ................
`);

const PROJ_AXE_THROWN = rows(`
  ................
  ................
  ........kkkk....
  .......k4443k...
  ......k44332kk..
  .....k43322khk..
  ......k322kkhk..
  .......kk..khk..
  ............kk..
  ................
  ................
  ................
  ................
  ................
  ................
  ................
`);

const PROJ_JAVELIN = rows(`
  ..............k.
  .............k4k
  ............k43k
  ...........khk..
  ..........khk...
  .........khk....
  ........khk.....
  .......khk......
  ......khk.......
  .....khk........
  ....khk.........
  ...khk..........
  ..khk...........
  ..kk............
  ................
  ................
`);

const PICKUP_KNIVES = rows(`
  ................
  ................
  ................
  ................
  ...k4k......k4k.
  ....k3k....k43k.
  ....khk....k3k..
  .....khk..khk...
  ......khk.khk...
  ......khkkhk....
  .......khhk.....
  .....kkkkkkkk...
  ....kzzzzzzzzk..
  .....kkkkkkkk...
  ................
  ................
`);

const PICKUP_AXES = rows(`
  ................
  ................
  ................
  ................
  ..kkkk......kkkk
  .k4443k....k4443
  .k4332kh..hk4332
  ..k32khkkkkhk32k
  ...kk..khhk..kk.
  ......khkkhk....
  .....khk..khk...
  ....khk....khk..
  ...kk........kk.
  ..kzzzzzzzzzzzzk
  ...kkkkkkkkkkkk.
  ................
`);

const PICKUP_JAVELINS = rows(`
  ............k4k.
  ...........k43k.
  ............k3k.
  ...........khk..
  ..........khk...
  .........khk....
  ........khk.k4k.
  .......khk..k3k.
  ......khk..khk..
  .....khk..khk...
  ....khk..khk....
  ...khk..khk.....
  ...kk...kk......
  ..kzzzzzzzzzzk..
  ...kkkkkkkkkk...
  ................
`);

const THROWN_PAL = {
  k: '#100d0a', h: '#7a5230', z: '#08060488',
  1: '#2a2a30', 2: '#55555e', 3: '#8a8a94', 4: '#d8d8e0',
};


// --- Traps ------------------------------------------------------------------
// Floor decals, drawn flat on the tile, so they read as part of the stonework
// until you are close enough to see the seam.

/**
 * Turned earth over something moving under the floor: a burrower's mound.
 * Dark soil ringing a raised crown of lighter crumbs, with a crack across it
 * and a few pale stones thrown up, so it reads as *freshly disturbed* at a
 * glance, not as floor texture. Drawn flat like a trap plate.
 */
const MOUND = rows(`
  ................
  ................
  .....aaaaaa.....
  ...aabbbbbbaa...
  ..abbbccccbbba..
  ..abbccddccbba..
  .abbccceccccbba.
  .abcccecccdccba.
  .abccdcceeccbba.
  .abbccccceccbba.
  ..abbccdcccbba..
  ..aabbbccbbbaa..
  ....aabbbbaa....
  ......aaaa......
  ................
  ................
`);

const TRAP_PLATE = rows(`
  ................
  ...pppppppppp...
  ..pqqqqqqqqqqp..
  ..pqrrrrrrrrqp..
  ..pqrssssssrqp..
  ..pqrsqqqqsrqp..
  ..pqrsq..qsrqp..
  ..pqrsq..qsrqp..
  ..pqrsq..qsrqp..
  ..pqrsq..qsrqp..
  ..pqrsqqqqsrqp..
  ..pqrssssssrqp..
  ..pqrrrrrrrrqp..
  ..pqqqqqqqqqqp..
  ...pppppppppp...
  ................
`);

const TRAP_SPIKES = rows(`
  ................
  ...pppppppppp...
  ..pkkkkkkkkkkp..
  ..pkwkkwkkwkkp..
  ..pkWkkWkkWkkp..
  ..pkkkkkkkkkkp..
  ..pkwkkwkkwkkp..
  ..pkWkkWkkWkkp..
  ..pkkkkkkkkkkp..
  ..pkwkkwkkwkkp..
  ..pkWkkWkkWkkp..
  ..pkkkkkkkkkkp..
  ..pkwkkwkkwkkp..
  ..pkkkkkkkkkkp..
  ...pppppppppp...
  ................
`);

const TRAP_WARD = rows(`
  ................
  .....cccccc.....
  ...cc......cc...
  ..c...dddd...c..
  .c...d....d...c.
  .c..d..dd..d..c.
  .c..d.d..d.d..c.
  .c..d.d..d.d..c.
  .c..d..dd..d..c.
  .c...d....d...c.
  ..c...dddd...c..
  ...cc......cc...
  .....cccccc.....
  ................
  ................
  ................
`);

const WARD_THRESHOLD = rows(`
  ................
  ....gggggggg....
  ..gg...bb...gg..
  .g.....bb.....g.
  .g............g.
  .g............g.
  .g............g.
  .gb....bb....bg.
  .gb....bb....bg.
  .g............g.
  .g............g.
  .g.....bb.....g.
  .g.....bb.....g.
  ..gg........gg..
  ....gggggggg....
  ................
`);

const TRAP_SPENT = rows(`
  ................
  ...pppppppppp...
  ..pqqqqqqqqqqp..
  ..pq........qp..
  ..pq........qp..
  ..pq........qp..
  ..pq........qp..
  ..pq........qp..
  ..pq........qp..
  ..pq........qp..
  ..pq........qp..
  ..pq........qp..
  ..pq........qp..
  ..pqqqqqqqqqqp..
  ...pppppppppp...
  ................
`);

// Sprung mechanisms stay readable as wreckage. Each keeps the same cold-iron
// frame but leaves a different failure pattern in its centre.
const TRAP_DART_SPENT = stamp(TRAP_SPENT, rows(`
  s......s
  .s....s.
  ..s..s..
  ...ss...
  ...rr...
  ..r..r..
  .r....r.
  r......r
`), 4, 4);

const TRAP_SPIKES_SPENT = stamp(TRAP_SPENT, rows(`
  k..k..k.
  w..w..w.
  k..k..k.
  ........
  .k..k...
  .w..w...
  .k..k...
`), 4, 4);

const TRAP_ALARM_SPENT = stamp(TRAP_SPENT, rows(`
  ..r..r..
  .r....r.
  r..rr..r
  ...rr...
  ...rr...
  r......r
  .r....r.
  ..r..r..
`), 4, 4);

// Cold iron against warm stone: the plates read by hue and value rather than by
// glowing, so spotting one is a matter of looking at the floor, not of the game
// pointing at it.
const TRAP_PAL = { p: '#08080a', q: '#44444e', r: '#6a6a76', s: '#9694a2' };


// An upright oval rift — the town portal a Scroll of Recall leaves behind.
// Taller than it is wide, and inset from the canvas edges, so standing next
// to one still leaves you a view of the corridor past it.
const TOWN_PORTAL = sym(rows(`
  ........
  ......cb
  .....cba
  ....cbaa
  ...cbaaw
  ...cbaaw
  ..cbaaww
  ..cbaaww
  ..cbaaww
  ..cbaaww
  ..cbaaww
  ..cbaaww
  ..cbaaww
  ..cbaaww
  ...cbaaw
  ...cbaaw
  ....cbaa
  .....cba
  ......cb
  ........
`));

export const PROPS: ArtDef[] = [
  { id: 'chest', palette: CHEST_PAL, rows: CHEST },
  { id: 'chest_mimic', palette: CHEST_PAL, rows: CHEST_MIMIC },
  { id: 'chest_open', palette: CHEST_PAL, rows: CHEST_OPEN },
  { id: 'chest_broken', palette: CHEST_PAL, rows: CHEST_BROKEN },
  { id: 'mimic_0', palette: CHEST_PAL, rows: MIMIC_IDLE },
  { id: 'mimic_atk', palette: CHEST_PAL, rows: MIMIC_ATK },
  { id: 'urn', palette: URN_PAL, rows: URN },
  { id: 'urn_broken', palette: URN_PAL, rows: URN_BROKEN },
  { id: 'barrel', palette: BARREL_PAL, rows: BARREL },
  { id: 'barrel_broken', palette: BARREL_PAL, rows: BARREL_BROKEN },
  { id: 'bones', palette: { k: '#1a150e', w: '#d8ccaa', v: '#9c8f72' }, rows: BONES },
  { id: 'shrine', palette: SHRINE_PAL, rows: SHRINE },
  { id: 'shrine_used', palette: SHRINE_PAL, rows: stamp(SHRINE, SHRINE_OFF) },
  { id: 'shrine_font', palette: { ...SHRINE_FONT_PAL, ...SHRINE_PROPS }, rows: SHRINE_FONT },
  { id: 'shrine_font_used', palette: { ...SHRINE_FONT_PAL, ...SHRINE_PROPS, ...SPENT }, rows: snuffed(SHRINE_FONT) },
  { id: 'shrine_idol', palette: { ...SHRINE_IDOL_PAL, ...SHRINE_PROPS }, rows: SHRINE_IDOL },
  { id: 'shrine_idol_used', palette: { ...SHRINE_IDOL_PAL, ...SHRINE_PROPS, ...SPENT }, rows: snuffed(SHRINE_IDOL) },
  { id: 'shrine_coffer', palette: { ...SHRINE_COFFER_PAL, ...SHRINE_PROPS }, rows: SHRINE_COFFER },
  { id: 'shrine_coffer_used', palette: { ...SHRINE_COFFER_PAL, ...SHRINE_PROPS, ...SPENT }, rows: snuffed(SHRINE_COFFER) },
  { id: 'shrine_blood', palette: { ...SHRINE_BLOOD_PAL, ...SHRINE_PROPS }, rows: SHRINE_BLOOD },
  { id: 'shrine_blood_used', palette: { ...SHRINE_BLOOD_PAL, ...SHRINE_PROPS, ...SPENT }, rows: snuffed(SHRINE_BLOOD) },
  { id: 'shrine_combat', palette: { ...SHRINE_COMBAT_PAL, ...SHRINE_PROPS }, rows: SHRINE_COMBAT },
  { id: 'shrine_combat_used', palette: { ...SHRINE_COMBAT_PAL, ...SHRINE_PROPS, ...SPENT }, rows: snuffed(SHRINE_COMBAT) },
  { id: 'fungus', palette: { k: '#0a1614', s: '#b8c8c0', c: '#28b0a0fa', d: '#90fff0fa', e: '#1a5a54', m: '#1e3a2a' }, rows: FUNGUS },
  { id: 'trap_dart', palette: TRAP_PAL, rows: TRAP_PLATE },
  { id: 'trap_spikes', palette: { p: '#08070a', k: '#14121a', w: '#8e8878', W: '#dcd4be' }, rows: TRAP_SPIKES },
  { id: 'trap_alarm', palette: { c: '#6a4a8afa', d: '#c890fffa' }, rows: TRAP_WARD },
  { id: 'ward_threshold', palette: { g: '#8a6a20fa', b: '#ffe8a0fa' }, rows: WARD_THRESHOLD },
  { id: 'ward_threshold_dim', palette: { g: '#453510fa', b: '#807450fa' }, rows: WARD_THRESHOLD },
  { id: 'trap_dart_spent', palette: TRAP_PAL, rows: TRAP_DART_SPENT },
  { id: 'trap_spikes_spent', palette: { ...TRAP_PAL, k: '#101014', w: '#aaa4b0' }, rows: TRAP_SPIKES_SPENT },
  { id: 'mound', palette: { a: '#2a1d12e0', b: '#5a4128', c: '#8a6842', d: '#d2bc94', e: '#120c06' }, rows: MOUND },
  { id: 'trap_alarm_spent', palette: TRAP_PAL, rows: TRAP_ALARM_SPENT },
  { id: 'town_portal', palette: { c: '#102848fa', b: '#2060b0fa', a: '#60b0fffa', w: '#d8f0fffa' }, rows: TOWN_PORTAL },
  { id: 'sconce', palette: { k: '#0c0c0e', i: '#3a3a42', j: '#5a5a64', h: '#5a3a18', g: '#3a2410', u: '#2a1a10', v: '#4a3020' }, rows: SCONCE },
  { id: 'flame_0', palette: FLAME_PAL, rows: FLAME_0 },
  { id: 'flame_1', palette: FLAME_PAL, rows: FLAME_1 },
  { id: 'flame_2', palette: FLAME_PAL, rows: FLAME_2 },
  { id: 'pickup_bag', palette: { k: '#140c06', t: '#8a6a40', u: '#6a4a28', v: '#4a3018', s: '#c8a870' }, rows: BAG },
  { id: 'pickup_gold', palette: { k: '#2a1a04', g: '#c09020', h: '#f0d050', y: '#fff4a0', o: '#806010' }, rows: GOLD_PILE },
  { id: 'proj_frost', palette: { 1: '#2050c0fa', 2: '#4a90f0fa', 3: '#90d0fffa', 4: '#d8f4fffa', w: '#fffffffa' }, rows: ORB },
  { id: 'proj_fire', palette: { 1: '#a02008fa', 2: '#e05010fa', 3: '#ffa030fa', 4: '#ffe080fa', w: '#fffff0fa' }, rows: ORB },
  { id: 'proj_shadow', palette: { 1: '#30104afa', 2: '#6020a0fa', 3: '#a060e0fa', 4: '#e0c0fffa', w: '#fffffffa' }, rows: ORB },
  { id: 'proj_arrow', palette: { k: '#1a1a1e', s: '#a0a0aa', h: '#8a6a40', f: '#d8d0c0' }, rows: ARROW },
  { id: 'proj_knife', palette: THROWN_PAL, rows: PROJ_KNIFE },
  { id: 'proj_axe_thrown', palette: THROWN_PAL, rows: PROJ_AXE_THROWN },
  { id: 'proj_javelin', palette: THROWN_PAL, rows: PROJ_JAVELIN },
  { id: 'pickup_knives', palette: THROWN_PAL, rows: PICKUP_KNIVES },
  { id: 'pickup_axes', palette: THROWN_PAL, rows: PICKUP_AXES },
  { id: 'pickup_javelins', palette: THROWN_PAL, rows: PICKUP_JAVELINS },
  ...([
    ['fire', '#ff8e25fa', '#fff1a8fa'],
    ['frost', '#64c7fffa', '#e4fafffa'],
    ['shadow', '#ab69effa', '#eed5fffa'],
    ['holy', '#ffdb63fa', '#fffad1fa'],
  ] as const).map(([element, tip, core]) => ({
    id: `proj_arrow_${element}`,
    palette: { k: '#1a1a1e', s: '#a0a0aa', h: '#8a6a40', f: '#d8d0c0', G: tip, H: core },
    rows: stamp(ARROW, rows(`
      ..G..
      .GHG.
      GHHHG
      .GHG.
      ..G..
    `), 10, 1),
  })),
];
