/**
 * Dev-only: stand where a bug report was filed.
 *
 * Reached with `?repro=<code>`, the code an in-game bug report puts in its
 * issue (see `src/systems/bug-report.ts`). Same contract as `./boss-arena`:
 * behind an `import.meta.env.DEV` guard at its one call site in `main.ts`, so
 * none of this reaches a production bundle.
 *
 * It rebuilds the reporter's *floor*, not their game: same seed, road, seals
 * and difficulty, descended in the same order so the shrine-pity rolls agree,
 * then the player is put on the reported tile facing the reported way. Walls,
 * doors, props and the strange-floor dressing match; what was alive, looted
 * or opened by then does not, and the kit is a fresh character's.
 */
import { GameState } from '../state/game-state';
import { World } from '../world/world';
import { WALL, generateFloor, tileAt } from '../systems/dungeon';
import { sealFloorMods } from '../data/seals';
import { startRun } from '../systems/run';
import { Repro, floorPrint } from '../systems/bug-report';

export function reproRoom(r: Repro) {
  return {
    prepare(state: GameState): void {
      if (r.difficulty) state.difficulty = r.difficulty;
      const run = startRun(state, r.seed);
      // Seals only apply once the King has fallen, which a scratch game has
      // not; set them on the run and relay floor one under their mods.
      if (r.seals?.length) {
        run.seals = r.seals;
        run.floors[0] = generateFloor(r.seed, 1, run.difficulty, false, undefined, sealFloorMods(run.seals));
      }
      if (r.road) run.road = r.road;
    },
    drop(world: World): string {
      while (world.run.depth < r.depth) world.changeFloorForTest('down');
      const f = world.floor;
      // A monster may be standing there in this copy; the reporter was, so
      // stand there anyway. Only a wall means the floor did not come out the same.
      const inside = r.x < f.width && r.y < f.height && tileAt(f, r.x, r.y) !== WALL;
      if (inside) world.placePlayer(r.x, r.y, r.facing);
      const where = `depth ${world.run.depth}, seed ${r.seed}, (${r.x}, ${r.y})`;
      if (r.print && r.print !== floorPrint(f)) {
        return `${where}. NOT the reported floor: it was generated by an older build. Check out the build named in the issue and try again`;
      }
      return inside ? where : `${where} is a wall here: the layout did not reproduce`;
    },
  };
}
